name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sqlite:
    runs-on: php8.5
    name: SQLite
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y unzip libsqlite3-dev
          docker-php-ext-install pdo_sqlite
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          composer update --prefer-stable --prefer-dist --no-interaction

      - name: Run tests
        run: vendor/bin/pest
        env:
          DB_CONNECTION: sqlite
